### ISSUE TITLE
请问支持导出证书直接软件加签，还是说必须依赖win上插物理key?

### ISSUE THREAD

**Issue by chenghonour** [Weasley-J/chinaport-data-signature#1]

**Comment by Weasley-J** [comment]
依赖于ukey，现在没法做但直接采用rsa脱机加密，ukey一定要插Windows电脑的。下一个版本打算把179加密和xml加密合成一个接口，还是要通过ukey加签，

**Comment by chenghonour** [comment]
原来如此。可以加下邮箱吗，同是跨境的，交流下。

**Comment by chenghonour** [comment]
> 依赖于ukey，现在没法做到直接采用rsa脱机加密，ukey一定要插Windows电脑的。下一个版本打算把179加密和xml加密合成一个接口，还是要通过ukey加签，里面的signValue值我推测和ukey无关，换句话就是你把你的数据给我加密，我把SignValue给你应给能用，华讯应该是这种方式，也就是华讯的在线加签远程服务器上面插着一个 电子口岸ukey的。还有中可能这算法是华讯做的。

原来如此。可以加下邮箱吗，同是跨境的，交流下。
