### ISSUE TITLE
启动了日志乱码问题

### ISSUE THREAD

**Issue by 2541864996** [Weasley-J/chinaport-data-signature#10]
![image](https://user-images.githubusercontent.com/56375288/224953224-ede881ae-9bc2-40ab-a966-f3b550eef02a.png)

**Comment by Weasley-J** [comment]
用的UTF-8编码，和Windows终端默认汉字会乱码，你可以查看查看同一级目录的log文件，用记事本打开，里面记录的是终端的输出内容，不会乱码。或者你使用gitbash启动试试。
