### ISSUE TITLE
WebSocketWrapper Bean实例并发读写问题

### ISSUE THREAD

**Issue by 7-1** [Weasley-J/chinaport-data-signature#11]
https://github.com/Weasley-J/chinaport-data-signature/blob/7935962fbccc3f18a5f8d4438952f705b094bb78/src/main/java/cn/alphahub/eport/signature/core/SignHandler.java#L110-L123

 `websocketClientHandler` Bean实例的 `webSocketWrapper`属性值没有考虑并发场景下的访问控制

**Comment by Weasley-J** [comment]
你好，感谢你的反馈，五一有点事要处理，我会在在后续的几天内会解决这个issue。

**Comment by Weasley-J** [comment]
> https://github.com/Weasley-J/chinaport-data-signature/blob/7935962fbccc3f18a5f8d4438952f705b094bb78/src/main/java/cn/alphahub/eport/signature/core/SignHandler.java#L110-L123
> 
> 
> 
>  `websocketClientHandler` Bean实例的 `webSocketWrapper`属性值没有考虑并发场景下的访问控制

你好，感谢你的反馈，五一有点事要处理，我会在在后续的几天内会解决这个issue

**Comment by Weasley-J** [comment]
> https://github.com/Weasley-J/chinaport-data-signature/blob/7935962fbccc3f18a5f8d4438952f705b094bb78/src/main/java/cn/alphahub/eport/signature/core/SignHandler.java#L110-L123
> 
> `websocketClientHandler` Bean实例的 `webSocketWrapper`属性值没有考虑并发场景下的访问控制

1.0.9版本已修复，采用原型模式
https://github.com/Weasley-J/chinaport-data-signature/blob/3e5d02b44233cf7474f71ccae22e497a91dbe223/src/main/java/cn/alphahub/eport/signature/config/InitialConfig.java#L196

**Comment by Weasley-J** [comment]
综合考虑使用原型模式
```java
@Bean
@Scope(scopeName = ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public WebSocketWrapper webSocketWrapper() {
    return new WebSocketWrapper();
}
```
https://github.com/Weasley-J/chinaport-data-signature/blob/3e5d02b44233cf7474f71ccae22e497a91dbe223/src/main/java/cn/alphahub/eport/signature/config/InitialConfig.java#L196
