### ISSUE TITLE
依赖要更新了xxx-M3的依赖都下不下来了

### ISSUE THREAD

**Issue by Liuerr0r** [Weasley-J/chinaport-data-signature#12]

**Comment by Weasley-J** [comment]
v1.0.9版本已解决此问题，本次版本升级更新：
- 升级 spring-cloud 至 2022.0.3
- 升级 spring-boot 至 3.1.0
- 升级 spring-cloud-alibaba 2022.0.0.0-RC2 （适配spring-boot 3.x.x ）
- WebSocket包装类Bean的实例对象使用原型模式，避免并发的数据安全问题
- dev的配置文件补全参数示例, key: eport.signature.ukey.health.endpoint.client-name
- 完善u-key加签异常时触发自动重启Windows Websocket客户端的逻辑，提高程序的健壮性
- 增加Ukey自我重启rpc调用接口，提供自动重启Windows Websocket客户端的手动触发逻辑
- 更新接口的Markdown和H5文档

**Comment by Weasley-J** [comment]
v1.0.9版本已解决此问题，本次版本升级更新：

升级 spring-cloud 至 2022.0.3
升级 spring-boot 至 3.1.0
升级 spring-cloud-alibaba 2022.0.0.0-RC2 （适配spring-boot 3.x.x ）
WebSocket包装类Bean的实例对象使用原型模式，避免并发的数据安全问题
dev的配置文件补全参数示例, key: eport.signature.ukey.health.endpoint.client-name
完善u-key加签异常时触发自动重启Windows Websocket客户端的逻辑，提高程序的健壮性
增加Ukey自我重启rpc调用接口，提供自动重启Windows Websocket客户端的手动触发逻辑
更新接口的Markdown和H5文档
