### ISSUE TITLE
大佬你好,我是2023年的新key,推送311报文,查看回执返回签名错误

### ISSUE THREAD

**Issue by abaijgz** [Weasley-J/chinaport-data-signature#14]
证书替换成了自己的证书,服务正常启动,返回正常.
下文是插入的签名参数:(貌似评论会吞掉<>这种格式错误,请忽略)
<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></ds:CanonicalizationMethod>
<ds:SignatureMethod Algorithm="http://www.chinaport.gov.cn/2022/04/xmldsig#sm2-sm3"></ds:SignatureMethod>
<ds:Reference URI="">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"></ds:Transform>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.chinaport.gov.cn/2022/04/xmldsig#sm3"></ds:DigestMethod>
<ds:DigestValue>{data["digestValue"]}</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue>
{data["signatureValue"]}
</ds:SignatureValue>
<ds:KeyInfo>
<ds:KeyName>{data["certNo"]}</ds:KeyName>
<ds:X509Data>
<ds:X509Certificate>
{data["x509Certificate"]}
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</ds:Signature>

**Comment by abaijgz** [comment]
有什么可能造成这种情况的原因?或者排查方向推荐吗

**Comment by Weasley-J** [comment]
> 有什么可能造成这种情况的原因?或者排查方向推荐吗

大概率是证书问题，你把u-key带着回去，晚点➕QQ看下

**Comment by Weasley-J** [comment]
> 有什么可能造成这种情况的原因?或者排查方向推荐吗

- xml字符串拼接拼接的有问题
- 证书有问题

 下载个社区版的idea跑跑[179的测试类](https://github.com/Weasley-J/chinaport-data-signature/blob/fbf3d8ebb95e351b48db8a0d38e77a1f1859e782/src/test/java/cn/alphahub/eport/signature/report/Report179Tests.java#L30)，看看控制台的推送结果，没有响应验签失败，就排除签名问题

**Comment by Weasley-J** [comment]
> 证书替换成了自己的证书,服务正常启动,返回正常. 下文是插入的签名参数:(貌似评论会吞掉<>这种格式错误,请忽略) <ds:Signature xmlns:ds="[http://www.w3.org/2000/09/xmldsig#">](http://www.w3.org/2000/09/xmldsig#%22%3E) ds:SignedInfo <ds:CanonicalizationMethod Algorithm="[http://www.w3.org/TR/2001/REC-xml-c14n-20010315">](http://www.w3.org/TR/2001/REC-xml-c14n-20010315%22%3E)</ds:CanonicalizationMethod> <ds:SignatureMethod Algorithm="[http://www.chinaport.gov.cn/2022/04/xmldsig#sm2-sm3">](http://www.chinaport.gov.cn/2022/04/xmldsig#sm2-sm3%22%3E)</ds:SignatureMethod> <ds:Reference URI=""> ds:Transforms <ds:Transform Algorithm="[http://www.w3.org/2000/09/xmldsig#enveloped-signature">](http://www.w3.org/2000/09/xmldsig#enveloped-signature%22%3E)</ds:Transform> </ds:Transforms> <ds:DigestMethod Algorithm="[http://www.chinaport.gov.cn/2022/04/xmldsig#sm3">](http://www.chinaport.gov.cn/2022/04/xmldsig#sm3%22%3E)</ds:DigestMethod> ds:DigestValue{data["digestValue"]}</ds:DigestValue> </ds:Reference> </ds:SignedInfo> ds:SignatureValue {data["signatureValue"]} </ds:SignatureValue> ds:KeyInfo ds:KeyName{data["certNo"]}</ds:KeyName> ds:X509Data ds:X509Certificate {data["x509Certificate"]} </ds:X509Certificate> </ds:X509Data> </ds:KeyInfo> </ds:Signature>



> 证书替换成了自己的证书,服务正常启动,返回正常. 下文是插入的签名参数:(貌似评论会吞掉<>这种格式错误,请忽略) <ds:Signature xmlns:ds="[http://www.w3.org/2000/09/xmldsig#">](http://www.w3.org/2000/09/xmldsig#%22%3E) ds:SignedInfo <ds:CanonicalizationMethod Algorithm="[http://www.w3.org/TR/2001/REC-xml-c14n-20010315">](http://www.w3.org/TR/2001/REC-xml-c14n-20010315%22%3E)</ds:CanonicalizationMethod> <ds:SignatureMethod Algorithm="[http://www.chinaport.gov.cn/2022/04/xmldsig#sm2-sm3">](http://www.chinaport.gov.cn/2022/04/xmldsig#sm2-sm3%22%3E)</ds:SignatureMethod> <ds:Reference URI=""> ds:Transforms <ds:Transform Algorithm="[http://www.w3.org/2000/09/xmldsig#enveloped-signature">](http://www.w3.org/2000/09/xmldsig#enveloped-signature%22%3E)</ds:Transform> </ds:Transforms> <ds:DigestMethod Algorithm="[http://www.chinaport.gov.cn/2022/04/xmldsig#sm3">](http://www.chinaport.gov.cn/2022/04/xmldsig#sm3%22%3E)</ds:DigestMethod> ds:DigestValue{data["digestValue"]}</ds:DigestValue> </ds:Reference> </ds:SignedInfo> ds:SignatureValue {data["signatureValue"]} </ds:SignatureValue> ds:KeyInfo ds:KeyName{data["certNo"]}</ds:KeyName> ds:X509Data ds:X509Certificate {data["x509Certificate"]} </ds:X509Certificate> </ds:X509Data> </ds:KeyInfo> </ds:Signature>

- `xml`中完整的`ds:Signature`节点格式应该是下面的这种（忽略xml的格式化问题，影响不大），其中`ds:X509Certificate`节点会自动从`ukey`中读, 应该是一行，我下面这个是格式化过的，正确的情况下不用格式化也能推送成功。

  - ```xml
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
      <ds:SignedInfo>
          <ds:CanonicalizationMethod
                  Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></ds:CanonicalizationMethod>
          <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"></ds:SignatureMethod>
          <ds:Reference URI="">
              <ds:Transforms>
                  <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"></ds:Transform>
              </ds:Transforms>
              <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"></ds:DigestMethod>
              <ds:DigestValue>SF/P+2sVsRQ9dJIqJSroW6ajb0Y=</ds:DigestValue>
          </ds:Reference>
      </ds:SignedInfo>
      <ds:SignatureValue>
          AI0wdcUHaaOR+FZ7W8lN6FrjzS+iru1qoBTCxm4S6knmLFLunPkLueELV69nYZr4x+uCPnNDD/wq
          jSqyPnH2xrrx8EFvsIhxNMCi+IlfS1z440YmeMEXnhff0pxSBGgrhETrq1tqp6QBZE5siBF4ow10
          0Q9RKaB+OMs4AB6I+0g=
      </ds:SignatureValue>
      <ds:KeyInfo>
          <ds:KeyName>0001</ds:KeyName>
          <ds:X509Data>
              <ds:X509Certificate>
                  MIIEWzCCA8SgAwIBAgIDAJknMA0GCSqGSIb3DQEBBQUAMHYxCzAJBgNVBAYTAmNuMREwDwYDVQQK
                  Hgh1NVtQU+NcuDENMAsGA1UECx4EAEMAQTENMAsGA1UECB4EUxdOrDEjMCEGA1UEAx4aTi1W/XU1
                  W1BT41y4ZXBjbk4tX8NfAFPRUzoxETAPBgNVBAceCE4cZblef1c6MB4XDTE1MDUxOTAwMDAwMFoX
                  DTQ5MTIwODAwMDAwMFowJTEjMCEGA1UEAx4aADEAM1P3W8aUpW1Li9VnDVKhVmhfAFPRUzowgZ8w
                  DQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAKoQc7txXMb5VuXJnALpKQ1mAxFW2hxPwRhXY0mirNIL
                  2gLY2z7ysqRvkpSRzr3BEq97xWLlXkQDG1QnzvTvh1YQzrffARSlCy6dYJ3YgM+Bps2NsPXhw1Lk
                  vk0wn7LXAskEbwRgLihu1pH6/IGEocgeFusWTXT6B/ppTiEXL/87AgMBAAGjggJGMIICQjALBgNV
                  HQ8EBAMCBsAwCQYDVR0TBAIwADCBoAYDVR0jBIGYMIGVgBQsaDiQrlh9ryILr2BYMK/wvmRvlqF6
                  pHgwdjELMAkGA1UEBhMCY24xETAPBgNVBAoeCHU1W1BT41y4MQ0wCwYDVQQLHgQAQwBBMQ0wCwYD
                  VQQIHgRTF06sMSMwIQYDVQQDHhpOLVb9dTVbUFPjXLhlcGNuTi1fw18AU9FTOjERMA8GA1UEBx4I
                  ThxluV5/VzqCASUwHQYDVR0OBBYEFPcD90hfpSLKzuhaE3NvhU1xwHDAMEIGA1UdIAQ7MDkwNwYG
                  K4EHAQECMC0wKwYIKwYBBQUHAgEWH2h0dHA6Ly9jcHMuY2hpbmFwb3J0Lmdvdi5jbi9DUFMwQgYD
                  VR0fBDswOTA3oDWgM4YxaHR0cDovL2xkYXAuY2hpbmFwb3J0Lmdvdi5jbjo4MDg4L2R6a2EwMDAt
                  MTk2LmNybDA9BggrBgEFBQcBAQQxMC8wLQYIKwYBBQUHMAGGIWh0dHA6Ly9vY3NwLmNoaW5hcG9y
                  dC5nb3YuY246ODA4ODAqBgorBgEEAalDZAUBBBwWGtbQufq159fTv9qwtsr9vt3W0NDEv6q3osf4
                  MBoGCisGAQQBqUNkBQYEDBYKUzAyMDEyMDAzODAaBgorBgEEAalDZAUJBAwWClMwMjAxMjAwMzgw
                  EgYKKwYBBAGpQ2QCBAQEFgJDQTASBgorBgEEAalDZAIBBAQWAjE5MBMGBSpWCwcFBAoWCLXn19O/
                  2rC2MA0GCSqGSIb3DQEBBQUAA4GBAFqdOOqCs/0zfJj5NM3UPXzAK/yIyx6b8ZEQXuY/aojzE46Q
                  QXX1/N+G3DsKPvUhXQj1mAsZQeT0aMiUa1aNCd0P8p+PsfrB9E5oZnFhp4cLDkkuh2gx+MCFOHe2
                  oEbi2/nCZpvWRJ34id5szTIw1n96/nrrg2+qFk+ddFr0xRzz
              </ds:X509Certificate>
          </ds:X509Data>
      </ds:KeyInfo>
     </ds:Signature>
    ```

  

- **4**个参数

  ![image-20230704004832397](https://weasley.oss-cn-shanghai.aliyuncs.com/Photos/image-20230704004832397.png)

**Comment by Weasley-J** [comment]
> > 证书替换成了自己的证书,服务正常启动,返回正常. 下文是插入的签名参数:(貌似评论会吞掉<>这种格式错误,请忽略) <ds:Signature xmlns:ds="[http://www.w3.org/2000/09/xmldsig#">](http://www.w3.org/2000/09/xmldsig#%22%3E) ds:SignedInfo <ds:CanonicalizationMethod Algorithm="[http://www.w3.org/TR/2001/REC-xml-c14n-20010315">](http://www.w3.org/TR/2001/REC-xml-c14n-20010315%22%3E)</ds:CanonicalizationMethod> <ds:SignatureMethod Algorithm="[http://www.chinaport.gov.cn/2022/04/xmldsig#sm2-sm3">](http://www.chinaport.gov.cn/2022/04/xmldsig#sm2-sm3%22%3E)</ds:SignatureMethod> <ds:Reference URI=""> ds:Transforms <ds:Transform Algorithm="[http://www.w3.org/2000/09/xmldsig#enveloped-signature">](http://www.w3.org/2000/09/xmldsig#enveloped-signature%22%3E)</ds:Transform> </ds:Transforms> <ds:DigestMethod Algorithm="[http://www.chinaport.gov.cn/2022/04/xmldsig#sm3">](http://www.chinaport.gov.cn/2022/04/xmldsig#sm3%22%3E)</ds:DigestMethod> ds:DigestValue{data["digestValue"]}</ds:DigestValue> </ds:Reference> </ds:SignedInfo> ds:SignatureValue {data["signatureValue"]} </ds:SignatureValue> ds:KeyInfo ds:KeyName{data["certNo"]}</ds:KeyName> ds:X509Data ds:X509Certificate {data["x509Certificate"]} </ds:X509Certificate> </ds:X509Data> </ds:KeyInfo> </ds:Signature>
> 
> > 证书替换成了自己的证书,服务正常启动,返回正常. 下文是插入的签名参数:(貌似评论会吞掉<>这种格式错误,请忽略) <ds:Signature xmlns:ds="[http://www.w3.org/2000/09/xmldsig#">](http://www.w3.org/2000/09/xmldsig#%22%3E) ds:SignedInfo <ds:CanonicalizationMethod Algorithm="[http://www.w3.org/TR/2001/REC-xml-c14n-20010315">](http://www.w3.org/TR/2001/REC-xml-c14n-20010315%22%3E)</ds:CanonicalizationMethod> <ds:SignatureMethod Algorithm="[http://www.chinaport.gov.cn/2022/04/xmldsig#sm2-sm3">](http://www.chinaport.gov.cn/2022/04/xmldsig#sm2-sm3%22%3E)</ds:SignatureMethod> <ds:Reference URI=""> ds:Transforms <ds:Transform Algorithm="[http://www.w3.org/2000/09/xmldsig#enveloped-signature">](http://www.w3.org/2000/09/xmldsig#enveloped-signature%22%3E)</ds:Transform> </ds:Transforms> <ds:DigestMethod Algorithm="[http://www.chinaport.gov.cn/2022/04/xmldsig#sm3">](http://www.chinaport.gov.cn/2022/04/xmldsig#sm3%22%3E)</ds:DigestMethod> ds:DigestValue{data["digestValue"]}</ds:DigestValue> </ds:Reference> </ds:SignedInfo> ds:SignatureValue {data["signatureValue"]} </ds:SignatureValue> ds:KeyInfo ds:KeyName{data["certNo"]}</ds:KeyName> ds:X509Data ds:X509Certificate {data["x509Certificate"]} </ds:X509Certificate> </ds:X509Data> </ds:KeyInfo> </ds:Signature>
> 
>     * `xml`中完整的`ds:Signature`节点格式应该是下面的这种（忽略xml的格式化问题，影响不大），其中`ds:X509Certificate`节点会自动从`ukey`中读, 应该是一行，我下面这个是格式化过的，正确的情况下不用格式化也能推送成功。
>       
>       * ```
>         <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
>           <ds:SignedInfo>
>               <ds:CanonicalizationMethod
>                       Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></ds:CanonicalizationMethod>
>               <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"></ds:SignatureMethod>
>               <ds:Reference URI="">
>                   <ds:Transforms>
>                       <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"></ds:Transform>
>                   </ds:Transforms>
>                   <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"></ds:DigestMethod>
>                   <ds:DigestValue>SF/P+2sVsRQ9dJIqJSroW6ajb0Y=</ds:DigestValue>
>               </ds:Reference>
>           </ds:SignedInfo>
>           <ds:SignatureValue>
>               AI0wdcUHaaOR+FZ7W8lN6FrjzS+iru1qoBTCxm4S6knmLFLunPkLueELV69nYZr4x+uCPnNDD/wq
>               jSqyPnH2xrrx8EFvsIhxNMCi+IlfS1z440YmeMEXnhff0pxSBGgrhETrq1tqp6QBZE5siBF4ow10
>               0Q9RKaB+OMs4AB6I+0g=
>           </ds:SignatureValue>
>           <ds:KeyInfo>
>               <ds:KeyName>0001</ds:KeyName>
>               <ds:X509Data>
>                   <ds:X509Certificate>
>                       MIIEWzCCA8SgAwIBAgIDAJknMA0GCSqGSIb3DQEBBQUAMHYxCzAJBgNVBAYTAmNuMREwDwYDVQQK
>                       Hgh1NVtQU+NcuDENMAsGA1UECx4EAEMAQTENMAsGA1UECB4EUxdOrDEjMCEGA1UEAx4aTi1W/XU1
>                       W1BT41y4ZXBjbk4tX8NfAFPRUzoxETAPBgNVBAceCE4cZblef1c6MB4XDTE1MDUxOTAwMDAwMFoX
>                       DTQ5MTIwODAwMDAwMFowJTEjMCEGA1UEAx4aADEAM1P3W8aUpW1Li9VnDVKhVmhfAFPRUzowgZ8w
>                       DQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAKoQc7txXMb5VuXJnALpKQ1mAxFW2hxPwRhXY0mirNIL
>                       2gLY2z7ysqRvkpSRzr3BEq97xWLlXkQDG1QnzvTvh1YQzrffARSlCy6dYJ3YgM+Bps2NsPXhw1Lk
>                       vk0wn7LXAskEbwRgLihu1pH6/IGEocgeFusWTXT6B/ppTiEXL/87AgMBAAGjggJGMIICQjALBgNV
>                       HQ8EBAMCBsAwCQYDVR0TBAIwADCBoAYDVR0jBIGYMIGVgBQsaDiQrlh9ryILr2BYMK/wvmRvlqF6
>                       pHgwdjELMAkGA1UEBhMCY24xETAPBgNVBAoeCHU1W1BT41y4MQ0wCwYDVQQLHgQAQwBBMQ0wCwYD
>                       VQQIHgRTF06sMSMwIQYDVQQDHhpOLVb9dTVbUFPjXLhlcGNuTi1fw18AU9FTOjERMA8GA1UEBx4I
>                       ThxluV5/VzqCASUwHQYDVR0OBBYEFPcD90hfpSLKzuhaE3NvhU1xwHDAMEIGA1UdIAQ7MDkwNwYG
>                       K4EHAQECMC0wKwYIKwYBBQUHAgEWH2h0dHA6Ly9jcHMuY2hpbmFwb3J0Lmdvdi5jbi9DUFMwQgYD
>                       VR0fBDswOTA3oDWgM4YxaHR0cDovL2xkYXAuY2hpbmFwb3J0Lmdvdi5jbjo4MDg4L2R6a2EwMDAt
>                       MTk2LmNybDA9BggrBgEFBQcBAQQxMC8wLQYIKwYBBQUHMAGGIWh0dHA6Ly9vY3NwLmNoaW5hcG9y
>                       dC5nb3YuY246ODA4ODAqBgorBgEEAalDZAUBBBwWGtbQufq159fTv9qwtsr9vt3W0NDEv6q3osf4
>                       MBoGCisGAQQBqUNkBQYEDBYKUzAyMDEyMDAzODAaBgorBgEEAalDZAUJBAwWClMwMjAxMjAwMzgw
>                       EgYKKwYBBAGpQ2QCBAQEFgJDQTASBgorBgEEAalDZAIBBAQWAjE5MBMGBSpWCwcFBAoWCLXn19O/
>                       2rC2MA0GCSqGSIb3DQEBBQUAA4GBAFqdOOqCs/0zfJj5NM3UPXzAK/yIyx6b8ZEQXuY/aojzE46Q
>                       QXX1/N+G3DsKPvUhXQj1mAsZQeT0aMiUa1aNCd0P8p+PsfrB9E5oZnFhp4cLDkkuh2gx+MCFOHe2
>                       oEbi2/nCZpvWRJ34id5szTIw1n96/nrrg2+qFk+ddFr0xRzz
>                   </ds:X509Certificate>
>               </ds:X509Data>
>           </ds:KeyInfo>
>          </ds:Signature>
>         ```
> 
>     * **4**个参数
>       ![image-20230704004832397](https://camo.githubusercontent.com/fbb7d8bc07092660cea88912d74984cb09b89aed48a9f2c4263b89f16b862c9b/68747470733a2f2f776561736c65792e6f73732d636e2d7368616e676861692e616c6979756e63732e636f6d2f50686f746f732f696d6167652d32303233303730343030343833323339372e706e67)

- 完整示例
<img width="1324" alt="图片" src="https://github.com/Weasley-J/chinaport-data-signature/assets/47849474/b874b751-22f3-4b56-a170-765a468f11f5">

**Comment by abaijgz** [comment]
我看 `海关跨境电商统一版系统密码产品选型和使用指南（202205版）.pdf` 里面将 sha1 算法拿掉了(2.1 支持 SM2 密码算法;2.2 支持 SM1、SM4 密码算法;2.3 支持 SM3 消息摘要算法),是不是海关那面不支持了

**Comment by Weasley-J** [comment]
> 我看 `海关跨境电商统一版系统密码产品选型和使用指南（202205版）.pdf` 里面将 sha1 算法拿掉了(2.1 支持 SM2 密码算法;2.2 支持 SM1、SM4 密码算法;2.3 支持 SM3 消息摘要算法),是不是海关那面不支持了

应该会兼容前面的算法，不兼容之前买的u-key使用会有问题

**Comment by abaijgz** [comment]
完全找不到问题,令人崩溃😭

**Comment by XuShall** [comment]
> > 有什么可能造成这种情况的原因?或者排查方向推荐吗
> 
> * xml字符串拼接拼接的有问题
> * 证书有问题
> 
> 下载个社区版的idea跑跑[179的测试类](https://github.com/Weasley-J/chinaport-data-signature/blob/fbf3d8ebb95e351b48db8a0d38e77a1f1859e782/src/test/java/cn/alphahub/eport/signature/report/Report179Tests.java#L30)，看看控制台的推送结果，没有响应验签失败，就排除签名问题

运行179的测试类,返回
```shell
{
    "code": "20000",
    "message": "certNo : certNo不为空;  signValue : signValue不为空;  ",
    "total": 0,
    "serviceTime": 1688468879495
}
```

**Comment by Weasley-J** [comment]
> ```shell
> 
> {
> 
>   "id": 1,
> 
>   "data": "\"sessionID\":\"ad2254-8hewyf32-55616249\"||\"payExchangeInfoHead\":\"{\"guid\":\"T9D55BA71-22DE-41F4-8B50-C36C83B3B530\",\"initalRequest\":\"原始请求\",\"initalResponse\":\"ok\",\"ebpCode\":\"4404840022\",\"payCode\":\"312226T001\",\"payTransactionId\":\"2018121222001354081010726129\",\"totalAmount\":100,\"currency\":\"142\",\"verDept\":\"3\",\"payType\":\"1\",\"tradingTime\":\"20181212041803\",\"note\":\"批量订单，测试订单优化,生成多个so订单\"}\"||\"payExchangeInfoLists\":\"[{\"orderNo\":\"SO1710301150602574003\",\"goodsInfo\":[{\"gname\":\"lhy-gnsku3\",\"itemLink\":\"http://m.yunjiweidian.com/yunjibuyer/static/vue-buyer/idc/index.html#/detail?itemId=999761&shopId=453\"},{\"gname\":\"lhy-gnsku2\",\"itemLink\":\"http://m.yunjiweidian.com/yunjibuyer/static/vue-buyer/idc/index.html#/detail?itemId=999760&shopId=453\"}],\"recpAccount\":\"OSA571908863132601\",\"recpCode\":\"\",\"recpName\":\"YUNJIHONGKONGLIMITED\"}]\"||\"serviceTime\":\"1544519952469\""
> 
> }
> 
> ```
> 
> 入餐参数,可以正常返回

你可以加我qq,有空我给你远程debug看看

**Comment by abaijgz** [comment]
> ```shell
> ```shell
> {
> 
>   "id": 1,
> 
>   "data": "\"sessionID\":\"ad2254-8hewyf32-55616249\"||\"payExchangeInfoHead\":\"{\"guid\":\"T9D55BA71-22DE-41F4-8B50-C36C83B3B530\",\"initalRequest\":\"原始请求\",\"initalResponse\":\"ok\",\"ebpCode\":\"4404840022\",\"payCode\":\"312226T001\",\"payTransactionId\":\"2018121222001354081010726129\",\"totalAmount\":100,\"currency\":\"142\",\"verDept\":\"3\",\"payType\":\"1\",\"tradingTime\":\"20181212041803\",\"note\":\"批量订单，测试订单优化,生成多个so订单\"}\"||\"payExchangeInfoLists\":\"[{\"orderNo\":\"SO1710301150602574003\",\"goodsInfo\":[{\"gname\":\"lhy-gnsku3\",\"itemLink\":\"http://m.yunjiweidian.com/yunjibuyer/static/vue-buyer/idc/index.html#/detail?itemId=999761&shopId=453\"},{\"gname\":\"lhy-gnsku2\",\"itemLink\":\"http://m.yunjiweidian.com/yunjibuyer/static/vue-buyer/idc/index.html#/detail?itemId=999760&shopId=453\"}],\"recpAccount\":\"OSA571908863132601\",\"recpCode\":\"\",\"recpName\":\"YUNJIHONGKONGLIMITED\"}]\"||\"serviceTime\":\"1544519952469\""
> 
> }
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 入餐参数,可以正常返回
> 
> 你可以加我qq,有空我给你远程debug看看
> ```

好的 大佬qq多少

**Comment by Weasley-J** [comment]
> > ```shell
> 
> > ```shell
> 
> > {
> 
> > 
> 
> >   "id": 1,
> 
> > 
> 
> >   "data": "\"sessionID\":\"ad2254-8hewyf32-55616249\"||\"payExchangeInfoHead\":\"{\"guid\":\"T9D55BA71-22DE-41F4-8B50-C36C83B3B530\",\"initalRequest\":\"原始请求\",\"initalResponse\":\"ok\",\"ebpCode\":\"4404840022\",\"payCode\":\"312226T001\",\"payTransactionId\":\"2018121222001354081010726129\",\"totalAmount\":100,\"currency\":\"142\",\"verDept\":\"3\",\"payType\":\"1\",\"tradingTime\":\"20181212041803\",\"note\":\"批量订单，测试订单优化,生成多个so订单\"}\"||\"payExchangeInfoLists\":\"[{\"orderNo\":\"SO1710301150602574003\",\"goodsInfo\":[{\"gname\":\"lhy-gnsku3\",\"itemLink\":\"http://m.yunjiweidian.com/yunjibuyer/static/vue-buyer/idc/index.html#/detail?itemId=999761&shopId=453\"},{\"gname\":\"lhy-gnsku2\",\"itemLink\":\"http://m.yunjiweidian.com/yunjibuyer/static/vue-buyer/idc/index.html#/detail?itemId=999760&shopId=453\"}],\"recpAccount\":\"OSA571908863132601\",\"recpCode\":\"\",\"recpName\":\"YUNJIHONGKONGLIMITED\"}]\"||\"serviceTime\":\"1544519952469\""
> 
> > 
> 
> > }
> 
> > ```
> 
> > 
> 
> > 
> 
> >     
> 
> >       
> 
> >     
> 
> > 
> 
> >       
> 
> >     
> 
> > 
> 
> >     
> 
> >   
> 
> > 入餐参数,可以正常返回
> 
> > 
> 
> > 你可以加我qq,有空我给你远程debug看看
> 
> > ```
> 
> 
> 
> 好的 大佬qq多少  

qq: 1432689025

**Comment by Weasley-J** [comment]
> 

ok

**Comment by Weasley-J** [comment]
> 

当前主分支的已增加主分支的算法自动推断，并且增加各个场景测试用例，望参考
