### ISSUE TITLE
大佬您好， 加签一定要搞一台电脑插ukey卡吗？

### ISSUE THREAD

**Issue by zhouguanghui123** [Weasley-J/chinaport-data-signature#15]

**Comment by Weasley-J** [comment]
需要台Windows电脑，海关u-key只支持Windows，

**Comment by Weasley-J** [comment]
已增加架构拓扑图，可以参考

**Comment by RickFallen** [comment]
> 已增加架构拓扑图，可以参考

理论上我拿到了ukey里的证书及公钥，只要按照SM3WITHSM2的算法去加签，是可以不用插ukey的吧？

**Comment by Weasley-J** [comment]
> > 已增加架构拓扑图，可以参考
> 
> 
> 
> 理论上我拿到了ukey里的证书及公钥，只要按照SM3WITHSM2的算法去加签，是可以不用插ukey的吧？

这个想法很好，不过生产环境我们还没这样验证过，你如果验证通过后，欢迎向我们提交pull request. 我们将更进一步完善这个项目

**Comment by RickFallen** [comment]
> > > 已增加架构拓扑图，可以参考
> > 
> > 
> > 理论上我拿到了ukey里的证书及公钥，只要按照SM3WITHSM2的算法去加签，是可以不用插ukey的吧？
> 
> 这个想法很好，不过生产环境我们还没这样验证过，你如果验证通过后，欢迎向我们提交pull request. 我们将更进一步完善这个项目

我还有个问题~ 我想调用Ukey中ws暴露的方法，比如 cus-sec_SpcSignDataAsPEM。那我怎么知道这个ws服务里都有哪些方法呢，这个有公开的文档吗？

**Comment by Weasley-J** [comment]
> > > > 已增加架构拓扑图，可以参考
> > > 
> > > 
> > > 理论上我拿到了ukey里的证书及公钥，只要按照SM3WITHSM2的算法去加签，是可以不用插ukey的吧？
> > 
> > 
> > 这个想法很好，不过生产环境我们还没这样验证过，你如果验证通过后，欢迎向我们提交pull request. 我们将更进一步完善这个项目
> 
> 我还有个问题~ 我想调用Ukey中ws暴露的方法，比如 cus-sec_SpcSignDataAsPEM。那我怎么知道这个ws服务里都有哪些方法呢，这个有公开的文档吗？

由于资料匮乏，暂时没有相关技术文档。

**Comment by Ralinly** [comment]
> > > 已增加架构拓扑图，可以参考
> > 
> > 
> > 理论上我拿到了ukey里的证书及公钥，只要按照SM3WITHSM2的算法去加签，是可以不用插ukey的吧？
> 
> 这个想法很好，不过生产环境我们还没这样验证过，你如果验证通过后，欢迎向我们提交pull request. 我们将更进一步完善这个项目

经测试是可以不插UKEY的，以SM3withSM2为例，生成SM3摘要后，使用证书的公钥对摘要进行SM2加密生成加签值即可
