### ISSUE TITLE
您好，想请教个问题

### ISSUE THREAD

**Issue by Mayumiran** [Weasley-J/chinaport-data-signature#16]
![image](https://github.com/Weasley-J/chinaport-data-signature/assets/33978109/e448be43-5541-4638-b9e3-d705e0979512)
推送311报文之后一直反馈验签失败 而且报错也是文档中不存在的状态码 属实难以理解，这边我用到的也是sm3或是sha1计算摘要 均失败了

**Comment by Weasley-J** [comment]
> ![image](https://user-images.githubusercontent.com/33978109/266283213-e448be43-5541-4638-b9e3-d705e0979512.png) 推送311报文之后一直反馈验签失败 而且报错也是文档中不存在的状态码 属实难以理解，这边我用到的也是sm3或是sha1计算摘要 均失败了

你好，最近工作日有点忙，这个问题我周末看看（0909/0910），

**Comment by Mayumiran** [comment]
感谢，可以的话 微信或者企鹅都能联系到我 870592450
