### ISSUE TITLE
大佬 为啥单一窗口文档中需要开通MQ通信方式而源码中未提及

### ISSUE THREAD

**Issue by lgcwn** [Weasley-J/chinaport-data-signature#17]
https://www.singlewindow.cn/#/documentDetail?cid=A01-sic-apply&ctype=1

**Comment by Weasley-J** [comment]
> > https://www.singlewindow.cn/#/documentDetail?cid=A01-sic-apply&ctype=1
> 
> 
> 
> 我大致看了，能实现功能，好像需要人工操作，效率有点低。开源这个项目的时候还没这个文档呢

不过并没有提到数据加签，成功率只有官方知道，
