### ISSUE TITLE
新版u-key加签问题

### ISSUE THREAD

**Issue by llogin** [Weasley-J/chinaport-data-signature#5]
您好，请问7月以后申请的u-key更换了加密算法，这个是不是不支持？

**Comment by llogin** [comment]
![image](https://user-images.githubusercontent.com/24217780/187187468-67fa94b5-cb74-49b5-b66b-41664193aca9.png)
报错信息

**Comment by Weasley-J** [comment]
> ![image](https://user-images.githubusercontent.com/24217780/187187468-67fa94b5-cb74-49b5-b66b-41664193aca9.png)
> 
> 报错信息

试试以下的方式：
1 检查下加签的数据格式，字符串是需要转义的
2 下载源码debug下，maven依赖在release里面下载

**Comment by Weasley-J** [comment]
> 您好，请问7月以后申请的u-key更换了加密算法，这个是不是不支持？

只要单一窗口的js文件没变，这个算法应该能用。

**Comment by llogin** [comment]
llogin@163.com

**Comment by llogin** [comment]
llogin@jd.com

**Comment by Weasley-J** [comment]
> 

1432689025@qq.com

**Comment by Weasley-J** [comment]
> [llogin@163.com](mailto:llogin@163.com),大佬，这是我邮箱，可否留个联系方式，沟通下

这个邮箱试试

**Comment by Weasley-J** [comment]
> [llogin@163.com](mailto:llogin@163.com),大佬，这是我邮箱，可否留个联系方式，沟通下

这个邮箱试试[1432689025@qq.com](mailto:1432689025@qq.com)

**Comment by Weasley-J** [comment]
> 您好，请问7月以后申请的u-key更换了加密算法，这个是不是不支持？

你好，因为这个算法是收费的，7月以后海关新颁发u-key可能修改了算法。你如果还没购买这个算法的话，可以尝试下载release中的maven依赖debug源码，调通以后可以提交PULL REQUEST. 我目前大概知道解决方案了，后面应该会解决。
