### ISSUE TITLE
大佬，加签过程优盾灭了求助

### ISSUE THREAD

**Issue by acfunOldDriver** [Weasley-J/chinaport-data-signature#7]
大佬，想咨询个问题，我们这边您的这个服务部署在linux云服务器上，优盾在内网的windows电脑上面，总是会出现一种问题就是优盾在收到数据后灯闪着闪着就灭了再也不亮了，然后就加签失败，想问一下这会是哪里的问题，有没有解决办法。

**Comment by Weasley-J** [comment]
解决方案：加签失败发送邮件提醒，下载源码在加签失败的哪里用Java调用CMD命令重启下UKEY客户端应该能解决你这个问题。CMD重启windows进程百度下cmd命令就好了

**Comment by Weasley-J** [comment]
https://github.com/Weasley-J/chinaport-data-signature/blob/main/src/main/java/cn/alphahub/eport/signature/core/WebSocketClientHandler.java#L90

**Comment by Weasley-J** [comment]
[这个类低90行的增加你调用CMD重启u-key客户端的逻辑](https://github.com/Weasley-J/chinaport-data-signature/blob/main/src/main/java/cn/alphahub/eport/signature/core/WebSocketClientHandler.java#L90)

**Comment by acfunOldDriver** [comment]
这个倒是一个思路，就是不理解为什么优盾会这么频繁的灭灯

**Comment by Weasley-J** [comment]
> 这个倒是一个思路，就是不理解为什么优盾会这么频繁的灭灯

你好，[Release v1.1.0版本](https://github.com/Weasley-J/chinaport-data-signature/releases)已支持自动重启ukey Websocket客户端的功能了，也支持加签算法自动推断，可以尝试升级试试。感谢你对我们项目的关注和支持。
